// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbewVDYtAk8DoxjL-OoLmWCkbr7dGmp60',
    appId: '1:482514270726:web:02567ecaeea26d91df2187',
    messagingSenderId: '482514270726',
    projectId: 'flutter-project-b57a0',
    authDomain: 'flutter-project-b57a0.firebaseapp.com',
    storageBucket: 'flutter-project-b57a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiAkCVwWA24X8PPl1Kw3P34Ijgs2f-nMw',
    appId: '1:482514270726:android:25cef20e4cb2e220df2187',
    messagingSenderId: '482514270726',
    projectId: 'flutter-project-b57a0',
    storageBucket: 'flutter-project-b57a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9TQ2SMTJIf8LMew8aPAesLj48xVtGSMM',
    appId: '1:482514270726:ios:18f5e894cfeb889cdf2187',
    messagingSenderId: '482514270726',
    projectId: 'flutter-project-b57a0',
    storageBucket: 'flutter-project-b57a0.appspot.com',
    iosBundleId: 'com.example.untitled',
  );
}
